from __future__ import annotations

# Encoding and defaults
UTF8_ENCODING = "utf-8"
DEFAULT_LOCALE = "en"
DEFAULT_ENVIRONMENT = "local"
DEFAULT_SCOPE = "all"
DEFAULT_FILE_EXTENSION = ".dart"
DEFAULT_ROOT_MARKER = "pubspec.yaml"
DEFAULT_INCLUDE_PATTERN = "*"
DEFAULT_MAX_WARNINGS = -1
TOP_OF_FILE_INLINE_SCAN_LIMIT = 10
EMPTY = ""

# Policy file names
CONFIG_FILE_NAME = "config.yaml"
MESSAGES_FILE_NAME = "messages.yaml"
SUPPRESSIONS_FILE_NAME = "suppressions.yaml"
BASELINE_FILE_NAME = "baseline.json"

# Common config keys
KEY_APPLIES_TO = "applies_to"
KEY_AUTHOR = "author"
KEY_AUTOFIX_AVAILABLE = "autofix_available"
KEY_AUTO_FIXABLE = "auto_fixable"
KEY_BASE_PATH = "base_path"
KEY_CATEGORY = "category"
KEY_CODE = "code"
KEY_COLUMN = "column"
KEY_CONFIDENCE = "confidence"
KEY_COST = "cost"
KEY_DESCRIPTION = "description"
KEY_DOCS = "docs"
KEY_DOCS_URL = "docs_url"
KEY_DURATION_MS = "duration_ms"
KEY_ENABLED = "enabled"
KEY_ERROR_COUNT = "error_count"
KEY_ERRORS = "errors"
KEY_EXAMPLES = "examples"
KEY_EXCLUDE = "exclude"
KEY_EXCLUDE_RULES = "exclude_rules"
KEY_EXIT_POLICY = "exit_policy"
KEY_EXPIRES_AT = "expires_at"
KEY_FAIL_ON = "fail_on"
KEY_FAMILIES = "families"
KEY_FILE_EXTENSION = "file_extension"
KEY_FILE_PATH = "file_path"
KEY_FILES = "files"
KEY_FILES_SCANNED = "files_scanned"
KEY_FIX_HINT_CODE = "fix_hint_code"
KEY_FIX_HINTS = "fix_hints"
KEY_FIX_TYPE = "fix_type"
KEY_FAMILY = "family"
KEY_GENERATED_AT = "generated_at"
KEY_ID = "id"
KEY_IMPACT = "impact"
KEY_IMPORT_PATTERN = "import_pattern"
KEY_INCLUDE = "include"
KEY_LAYER_DETECTION_PATTERN = "layer_detection_pattern"
KEY_LEVEL = "level"
KEY_LINE_NUMBER = "line_number"
KEY_LOCALE = "locale"
KEY_MAX_COST = "max_cost"
KEY_MAX_WARNINGS = "max_warnings"
KEY_MESSAGE = "message"
KEY_MESSAGE_CODE = "message_code"
KEY_MESSAGE_PARAMS = "message_params"
KEY_MESSAGES = "messages"
KEY_META = "meta"
KEY_METHOD_PATTERN = "method_pattern"
KEY_MIN_COUNT = "min_count"
KEY_NAME = "name"
KEY_OVERRIDES = "overrides"
KEY_OWNER = "owner"
KEY_PARAMS = "params"
KEY_PATHS = "paths"
KEY_PATTERN = "pattern"
KEY_PATTERNS = "patterns"
KEY_PER_CHILD_REQUIRED = "per_child_required"
KEY_PLAYBOOK = "playbook"
KEY_PROFILES = "profiles"
KEY_PROJECT = "project"
KEY_REASON = "reason"
KEY_REQUIRED_ANY = "required_any"
KEY_REQUIRED_DIRS = "required_dirs"
KEY_REQUIRED_FILES = "required_files"
KEY_REQUIRED_MEMBERS = "required_members"
KEY_REQUIRED_RULES = "required_rules"
KEY_REQUIRES_AST = "requires_ast"
KEY_REQUIRES_PROJECT_SCAN = "requires_project_scan"
KEY_RESULTS = "results"
KEY_ROOT_MARKER = "root_marker"
KEY_ROOTS = "roots"
KEY_RULE_FILES = "rule_files"
KEY_RULE_ID = "rule_id"
KEY_RULE_NAME = "rule_name"
KEY_RULES = "rules"
KEY_SCHEMA_VERSION = "schema_version"
KEY_SCOPE = "scope"
KEY_SCOPES = "scopes"
KEY_SEVERITY = "severity"
KEY_SKIP_COMMENTS = "skip_comments"
KEY_STABLE = "stable"
KEY_SUGGESTION = "suggestion"
KEY_SUMMARY = "summary"
KEY_SUPPORTS_INCREMENTAL = "supports_incremental"
KEY_SUPPRESSIONS = "suppressions"
KEY_SYMBOL = "symbol"
KEY_TAGS = "tags"
KEY_TARGETS = "targets"
KEY_TEXT = "text"
KEY_TYPE = "type"
KEY_URL = "url"
KEY_VIOLATION_COUNT = "violation_count"
KEY_VIOLATIONS = "violations"
KEY_VIOLATIONS_PREVIEW = "violations_preview"
KEY_WARNING_COUNT = "warning_count"
KEY_WARNINGS = "warnings"

# Matcher and handler values
KEY_CLASS_PATTERN = "class_pattern"
KEY_EXPECTED_CHILDREN = "expected_children"
KEY_FORBIDDEN = "forbidden"
KEY_FORBIDDEN_EXACT = "forbidden_exact"
KEY_FORBIDDEN_IMPORT_PATHS = "forbidden_import_paths"
KEY_FORBIDDEN_IMPORTS = "forbidden_imports"
HANDLER_MODE_FILE = "file"
HANDLER_MODE_PROJECT = "project"
RULE_TYPE_AST_CHECK = "ast_check"
RULE_TYPE_FILE_EXISTENCE = "file_existence"
RULE_TYPE_FORBIDDEN_PATTERN = "forbidden_pattern"
RULE_TYPE_FORBIDDEN_TOKEN = "forbidden_token"
RULE_TYPE_IMPORT_DIRECTION = "import_direction"
RULE_TYPE_NAMING_CONVENTION = "naming_convention"
RULE_TYPE_PATH_STRUCTURE = "path_structure"
RULE_TYPE_PROJECT_CHECK = "project_check"
RULE_TYPE_REQUIRED_ANY_TOKEN = "required_any_token"
RULE_TYPE_REQUIRED_IN_CLASS = "required_in_class"
RULE_TYPE_REQUIRED_PATTERN = "required_pattern"
RULE_TYPE_STRUCTURAL_CHECK = "structural_check"

# Cost handling
COST_LOW = "low"
COST_MEDIUM = "medium"
COST_HIGH = "high"
MAX_COST_CHOICES = (COST_LOW, COST_MEDIUM, COST_HIGH)
COST_ORDER = {
    COST_LOW: 0,
    COST_MEDIUM: 1,
    COST_HIGH: 2,
}

# Output formats and statuses
FORMAT_TERMINAL = "terminal"
FORMAT_JSON = "json"
FORMAT_MARKDOWN = "markdown"
SUPPORTED_FORMATS = (
    FORMAT_TERMINAL,
    FORMAT_JSON,
    FORMAT_MARKDOWN,
)
STATUS_ENABLED = "enabled"
STATUS_DISABLED = "disabled"
STATUS_PASS = "PASS"
STATUS_FAIL = "FAIL"

# Inline suppression markers
INLINE_SUPPRESSION_FILE_PREFIX = "guard-ignore-file: "
INLINE_SUPPRESSION_PREFIX = "guard-ignore: "
INLINE_SUPPRESSION_NEXT_LINE_PREFIX = "guard-ignore-next-line: "
